 

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
      - DB_HOST=xcow0g8cwkgkgwggw4kko0s0
      - DB_USER=mysql
      - DB_PASS=G11avYQ2gtsAN0Sx58u8QSOUEDoBhWnPDUydzv720s9Z4s2OHcirA7rnzOSLcyLC
      - DB_NAME=inventario_db
    volumes:
      - ./:/var/www/html
    networks:
      - coolify
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: xcow0g8cwkgkgwggw4kko0s0
    environment:
      - MYSQL_ROOT_PASSWORD=G11avYQ2gtsAN0Sx58u8QSOUEDoBhWnPDUydzv720s9Z4s2OHcirA7rnzOSLcyLC
      - MYSQL_DATABASE=inventario_db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=G11avYQ2gtsAN0Sx58u8QSOUEDoBhWnPDUydzv720s9Z4s2OHcirA7rnzOSLcyLC
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  coolify:
    external: true

volumes:
  mysql_data:
