version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - coolify
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: xcow0g8cwkgkgwggw4kko0s0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - coolify
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  coolify:
    external: true

volumes:
  mysql_data:
